server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: 47.101.37.83
      port: 8510
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}